name: Deploy Node.js to Azure Web App

on:
  [push]

env:
  AZURE_WEBAPP_NAME: algo-visualizer
  AZURE_WEBAPP_PACKAGE_PATH: './dist/algo-visualizer'
  NODE_VERSION: '14.18.1'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        npm install
        npm run build -- --prod
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}